### ISSUE TITLE
Support Jellyfin API

### ISSUE THREAD

**Issue by jeffvli** [jeffvli/sonixd#87]
**Is your feature request related to a problem? Please describe.**
Add support for Jellyfin's music server API

**Describe the solution you'd like**
1. Add a selector between Subsonic & Jellyfin when logging into Sonixd
2. Normalize API endpoints and add a controller to plug in both Subsonic and Jellyfin APIs

**Describe alternatives you've considered**
N/a

**Additional context**
Jellyfin API reference: https://api.jellyfin.org/

Existing projects that implement Jellyfin audio API:
- Jellyfin media player - https://github.com/jellyfin/jellyfin-media-player
- Jellyfin web - https://github.com/jellyfin/jellyfin-web#getting-started
- Jellyfin vue - https://github.com/jellyfin/jellyfin-vue
- Jellyamp - https://github.dev/m0ngr31/jellyamp/
- Jellycli - https://github.com/tryffel/jellycli

# Tasks

- [x] Add generic type schema for overall application
- [x] Add api controller to route commands for specified server type (jellyfin/subsonic)
  - [x] Player
    - [x] Auto playlist (random songs)
  - [x] Browse playlists
    - [x] Add playlists
    - [x] Remove playlists
    - [x] Edit playlists
  - [x] Browse albums
  - [x] Browse favorites
    - [x] Add favorites
    - [x] Remove favorites
  - [x] Browse genres
  - [x] Browse artists
  - [x] Browse folders
  - [x] Download artist/albums
  - [x] Search
  - [x] Set music folder
  - [x] Scrobble (played/progress)
  - [x] Scan library (No way to get scan status?)
  - Set ratings (Not applicable in Jellyfin)
